- Billing.API.Test/InvoiceApiTest.cs
- Billing.API/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs
- Billing.API/DopplerSecurity/IsSuperUserHandler.cs
- Billing.API/DopplerSecurity/IsSuperUserRequirement.cs
- Billing.API/Startup.cs
Doppler needs to be able to get Invoice information for any client.
Based on the https://github.com/FromDoppler/doppler-custom-domain/pull/13 work, the same logic was applied here
> Add super user validation

- Billing.API.Test/Billing.API.Test.csproj
- Billing.API/Billing.API.csproj
- Billing.API/Controllers/InvoiceController.cs
- Billing.API/Services/Invoice/DummyInvoiceProviderService.cs
- Billing.API/Services/Invoice/IInvoiceService.cs
- Billing.API/Services/Invoice/InvoiceService.cs
Since Net Core DLL for SAP Hana is not confirmed to work 100% with Linux/Mac, some connection tests are needed to determine if the DLL is working or not.
Added a method with Try/Catch in order to determine if there is an error while connecting to database.
> SAP Hana Tests

- Jenkinsfile
[Swarm PR to add PROD TEST](https://github.com/MakingSense/doppler-swarm/pull/191)
> Billing PROD TEST

- .prettierignore
- Billing.API/appsettings.Development.json
- Billing.API/appsettings.json
- package.json
Hi @rockambole86, @FromDoppler/sap and @FromDoppler/doppler-melmac,
These are all minor changes in order to remove warnings, fix editor config validation inside docker, and make appsettings cleaner. 
Could you review?
> Minor cleaning

- Billing.API.Test/Billing.API.Test.csproj
- Billing.API.Test/InvoiceApiTest.cs
- Billing.API.Test/InvoiceApiValidationTest.cs
- Billing.API/Billing.API.csproj
- Billing.API/Controllers/InvoiceController.cs
- Billing.API/Extensions/InvoiceServiceCollectionExtensions.cs
- Billing.API/Models/InvoiceListItem.cs
- Billing.API/Properties/launchSettings.json
- Billing.API/Services/Invoice/DummyInvoiceService.cs
- Billing.API/Services/Invoice/IInvoiceService.cs
- Billing.API/Services/Invoice/InvoiceService.cs
- Billing.API/Startup.cs
- README.md
Needed to correct the endpoint URL
Changed the endpoint URL form `/invoinces/{clientId}` -> `/accounts/{origin}/{clientId}/invoices`
> Endpoint URL

- build-n-publish.sh
When the image is Windows-based, the suffix `-windows` is added to each one of the image tags.
Also, the platform (`linux` or `windows`) is included in the version.txt file, for example: 
```
v1.1.0+301942387a2d11e47dec35138e0c18fcd91a515f-linux
```
Or
```
v1.1.0+301942387a2d11e47dec35138e0c18fcd91a515f-windows
```
> Support building Windows-based images

- Billing.API/Controllers/InvoiceController.cs
- Billing.API/Models/PaginatedResult.cs
- Billing.API/Services/Invoice/DummyInvoiceService.cs
- Billing.API/Services/Invoice/IInvoiceService.cs
- Billing.API/Services/Invoice/InvoiceService.cs
Implemented the pagination in the invoices endpoint:
Now the endpoint returns a new obejct: **PaginatedResult<InvoiceListItem>**. The object contains a list of the Paginated Items and also the total of the all items.
> DAT-85-Implement pagination in the invoices endpoint

- Billing.API/Models/InvoiceListItem.cs
- Billing.API/Services/Invoice/DummyInvoiceService.cs
- README.md
Rename Link property in the InvoiceListItem by FileName:
> DAT-97: rename "link" by "fileName"

- Billing.API/Startup.cs
@FromDoppler/sap, at the end it was only something that I had missed.
> fix: add missing static files configuration

- build-n-publish.sh
> fix: fix version.txt content in final versions

- Billing.API/Services/Invoice/InvoiceService.cs
We test with real data and detect inconsistency between Invoices list in the amount field
UI
PDF
> [DAT-143] Fix Hanna consult

- Billing.API/appsettings.Development.json
- Billing.API/appsettings.json
We detect a problem in production, the invoices are located in the test environment TEST_MSARG for the production environment, it should be MSARGPROD for production services
> [DAT-149] Fix schema db in prod environment

- Billing.API/Services/Invoice/InvoiceService.cs
We detect a problem in the SQL sentence for Get invoices list, the invoices are duplicate
Example
@MarianoHerrera could you review it?
> [DAT-151] Fix duplicate invoices

- Billing.API/DopplerSecurity/IsOwnResourceHandler.cs
- Billing.API/DopplerSecurity/IsSuperUserHandler.cs
I made some mistakes in 4b504359ae83fb847f36161aedc58f13eb2a2d91
It did not allow to configure authorization handlers dinamically using the generic type.
> fix(authorization): fix wrong code in authorization handlers

- Billing.API.Test/Billing.API.Test.csproj
- Billing.API.Test/InvoiceApiTest.cs
- Billing.API/Billing.API.csproj
- Billing.API/Controllers/InvoiceController.cs
- Billing.API/DopplerSecurity/CryptoHelper.cs
- Billing.API/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs
- Billing.API/DopplerSecurity/IsOwnResourceHandler.cs
- Billing.API/DopplerSecurity/IsSuperUserOrOwnResourceOrValidSignatureRequirement.cs
- Billing.API/DopplerSecurity/IsValidSignatureHandler.cs
- Billing.API/DopplerSecurity/IsValidSignatureRequirement.cs
###Background
Since the web application is already in production, we need to allow backward compatibility with it, in order to be able to download the files either by authenticating with Token or validating the signature.
###Changes done
- Added requirement to validate the signature
- Removed the `AllowAnonymous` annotation to the method for downloading files, so the requirements are processed
- Added unit tests
> Download invoice files (backward compatibility)

- Billing.API/Models/InvoiceListItem.cs
- Billing.API/Services/Invoice/DummyInvoiceService.cs
- Billing.API/Services/Invoice/InvoiceService.cs
Included the "Credit Notes" into the invoices list:
**Changes:**
- Updated Hana's query to include also the information about "Credit Notes".
- Added two new properties: DocumentType ("NC" for "Credit Notes" and "FC" for invoices) and DocumentNumber (For example: A-0001-0000000050)  to indentify the document.
**Task:** [DAT-167](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-167)
> feat (invoices): include the credit notes into the invoices list

- Billing.API.Test/InvoiceApiTest.cs
- Billing.API/Controllers/InvoiceController.cs
- Billing.API/Models/InvoiceConfig.cs
- Billing.API/Services/Invoice/DummyInvoiceService.cs
- Billing.API/Services/Invoice/IInvoiceService.cs
- Billing.API/Services/Invoice/ISapServiceSettingsService.cs
- Billing.API/Services/Invoice/InvoiceProviderOptions.cs
- Billing.API/Services/Invoice/InvoiceService.cs
- Billing.API/Services/Invoice/InvoiceServiceCollectionExtensions.cs
- Billing.API/Services/Invoice/SapServiceSettingsService.cs
- Billing.API/appsettings.json
Integrated with the SAP of the US
**Changes:**
- Retrieved invoices from AR o US Sap System.
- Updated the url to get invoice file to include the Sap System. For example: ```accounts/doppler/2/invoices/invoice_AR_2020-09-11_4194.pdf```
-  Added new endpoint to check the connection with US Sap.
- Added new UTs to validate the Sap System.
**Task:** [DAT-191](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-191)
> feat: integrated with the SAP of the US

- Billing.API/appsettings.json
Update config to use PROD SAP
Task: [DAT-224](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-224)
> feat: update prod config

- package.json
Hi team, it seems that I forgot something in #22, it should fix it.
> chore: restore prettier validation

- Billing.API/Billing.API.csproj
> [DAT-473] - Update dependabot

- .github/dependabot.yml
Remove unnecessary Dependabot updates
> feat: Remove unnecessary dependabot

- Billing.API.Test/Billing.API.Test.csproj
- Billing.API/Billing.API.csproj
> feat: [DAT-519] Update dependabot dependences

- Billing.API/appsettings.json
We change url for a new Sap server
> feat: Change url for new sap server

- Billing.API/Models/DocumentList.cs
- Billing.API/Services/SapApi/SapApiService.cs
- Billing.API/appsettings.json
Fix issue when get invoices from SAP
> [No ticket] - Fix issue get invoices

- Billing.API/Services/Invoice/InvoiceProviderOptions.cs
- Billing.API/appsettings.json
Jira Ticket: [DAT-1423](https://makingsense.atlassian.net/browse/DAT-1423)
Remove unused db connection string from project.
[DAT-1423]: https://makingsense.atlassian.net/browse/DAT-1423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-1423] -remove db connection string

- Billing.API/appsettings.json
Add new prefix for the invoices
**Task:** [DAT-2008](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2008)
[DAT-2008]: https://makingsense.atlassian.net/browse/DAT-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2008] - Add new prefix for the invoices

- Billing.API/Controllers/InvoiceController.cs
- Billing.API/Models/DelinquentCustomerAndInvoice.cs
- Billing.API/Models/UnpaidInvoice.cs
- Billing.API/Services/Invoice/DummyInvoiceService.cs
- Billing.API/Services/Invoice/IInvoiceService.cs
- Billing.API/Services/Invoice/InvoiceService.cs
- Billing.API/Services/SapApi/DelinquentCustomerAndInvoice.cs
- Billing.API/Services/SapApi/GetDelinquentCustomersAndInvoicesResponse.cs
- Billing.API/Services/SapApi/ISapApiService.cs
- Billing.API/Services/SapApi/SapApiService.cs
Add new endpoint to get the delinquent customer and invoices.
**Task:** [DAT-2304](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2304)
[DAT-2304]: https://makingsense.atlassian.net/browse/DAT-2304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2304] - Add new endpoint to get the delinquent customer and invoices

- Billing.API/Models/DelinquentCustomerAndInvoice.cs
- Billing.API/Services/Invoice/DummyInvoiceService.cs
- Billing.API/Services/Invoice/InvoiceService.cs
- Billing.API/Services/SapApi/DelinquentCustomerAndInvoice.cs
- Billing.API/Services/SapApi/GetContactEmployeesResponse.cs
- Billing.API/Services/SapApi/SapApiService.cs
- Billing.API/Services/SapApi/SapContactEmployee.cs
Add dummy data and update the endpoint
Task: [DAT-2304](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2304)
[DAT-2304]: https://makingsense.atlassian.net/browse/DAT-2304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2304] - Add dummy data and update the endpoint

- Billing.API/Services/Invoice/DummyInvoiceService.cs
> [No-task] - Update dummy data

- Billing.API/Controllers/InvoiceController.cs
- Billing.API/Services/Invoice/DummyInvoiceService.cs
- Billing.API/Services/Invoice/IInvoiceService.cs
- Billing.API/Services/Invoice/InvoiceService.cs
Add includePaymentTerms parameter to get unpaid invoces from sap
> [no-task] - Add includePaymentTerms parameter to get unpaid invoces from sap

- Billing.API/Services/Invoice/InvoiceService.cs
- Billing.API/Services/SapApi/GetPaymentTermsTypeByIdResponse.cs
- Billing.API/Services/SapApi/GetPaymentTermsTypesResponse.cs
- Billing.API/Services/SapApi/ISapApiService.cs
- Billing.API/Services/SapApi/SapApiService.cs
Add endpoint to get all payment terms types
> [no-task] - Add endpoint to get all payment terms types

- Billing.API/Services/Invoice/InvoiceService.cs
Fix issue when return the invoices.
**Task:** [DAT-2543](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2543)
[DAT-2543]: https://makingsense.atlassian.net/browse/DAT-2543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2543] - Fix issue when return the invoices
